server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz2wsx!E